[tools]
bat = "latest"
cmake = "latest"
fd = "latest"
fzf = "latest"
ghq = "latest"
lazygit = "latest"
lua = "5.1"
ninja = "latest"
node = "latest"
pnpm = "latest"
ripgrep = "latest"
rust-analyzer = "latest"
shfmt = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
