# [[plugins]]
# repo = 'Shougo/vinarise'
# on_cmd = ['Vinarise']

# [[plugins]]
# repo = 'thinca/vim-quickrun'
# on_cmd = ['QuickRun']
# hook_add = '''
#   if !exists("g:quickrun_config")
#     let g:quickrun_config = {}
#   endif
#   let g:quickrun_config = {
#     \  "_" : {
#     \    "outputter/buffer/split" : ":botright 8sp",
#     \    "runner" : "vimproc",
#     \    "runner/vimproc/updatetime" : 40,
#     \  }
#     \}
# '''


# [[plugins]]
# repo = 'sjl/gundo.vim'
# on_cmd = ['GundoShow']


[[plugins]]
repo = 'h1mesuke/vim-alignta'
on_cmd =  ['Alignta']


# GIT {{{
[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd=['Gstatus', 'Gwrite', 'Gread', 'Gcommit', 'Gdiff', 'Gvdiff']

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event=['VimEnter']
# }}} GIT


# syntax {{{
[[plugins]]
repo = 'sirtaj/vim-openscad'
on_ft = ['scad']
# }}} syntax


# # LANG C {{{
# [[plugins]]
# repo = 'justmao945/vim-clang'
# on_ft = ['c', 'cpp']
# hook_add = '''
#   let g:clang_auto = 0
#   let g:clang_c_completeopt = 'menuone'
#   let g:clang_cpp_completeopt = 'menuone'
#   let g:clang_cpp_options = '-std=c++14 -stdlib=libc++'
# '''
#
# }}} LANG C



# HTML {{{
[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['css', 'html', 'javascript', 'markdown', 'typescript', ]

# [[plugins]]
# repo  = 'hokaccha/vim-html5validator'
# on_ft = ['html', 'javascript', 'typescript',]

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# on_ft = ['html', 'javascript', 'typescript',]

# [[plugins]]
# repo = 'jason0x43/vim-js-indent'
# on_ft = ['html', 'javascript', 'typescript',]

# [[plugins]]
# repo = 'othree/javascript-libraries-syntax.vim'
# on_ft = ['html', 'javascript', 'typescript',]

# [[plugins]]
# repo = 'leafgarland/typescript-vim'
# on_ft = ['typescript']
# hook_add = '''
#   let g:js_indent_typescript = 1
# '''

#[[plugins]]
#repo  = 'clausreinke/typescript-tools'
#on_ft = ['typescript']

# }}} HTML


# others {{{
# [[plugins]]
# repo = 'chrisbra/csv.vim'
# on_ft = ['csv']

# Rust {{{
# move to polyglot
# [[plugins]]
# repo = 'rust-lang/rust.vim'
# on_ft = ['rust']
# hook_add = '''
#   let g:rustfmt_autosave = 1
# '''
# }}} Rust

# fzf {{{
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
on_cmd  = ['Files', 'GFiles', 'GFlies?', 'Snippets']
# }}} fzf
