[[plugins]]
repo    = 'Shougo/vimfiler'
on_cmd  = ['VimFiler', 'VimFilerExplorer']
depends = ['unite.vim']
hook_add = '''
  nnoremap <F2> :VimFiler -buffer-name=explorer -split -winwidth=45 -toggle -no-quit
'''

[[plugins]]
repo = 'Shougo/vimshell'
on_cmd = ['VimShell']

[[plugins]]
repo = 'Shougo/vinarise'
on_cmd = ['Vinarise']

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = ['QuickRun']
hook_add = '''
  if !exists("g:quickrun_config")
    let g:quickrun_config = {}
  endif
  let g:quickrun_config = {
    \  "_" : {
    \    "outputter/buffer/split" : ":botright 8sp",
    \    "runner" : "vimproc",
    \    "runner/vimproc/updatetime" : 40,
    \  }
    \}
'''


[[plugins]]
repo = 'sjl/gundo.vim'
on_cmd = ['GundoShow']


[[plugins]]
repo = 'yuratomo/w3m.vim'
on_cmd = ['W3m', 'W3mTab']


[[plugins]]
repo = 'h1mesuke/vim-alignta'
on_cmd =  ['Alignta']


# GIT {{{
[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Gstatus']
# }}} GIT


# syntax {{{
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
# }}}


# HASKELL {{{
[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']
hook_add = '''
  let g:haskellmode_completion_ghc = 0
  autocmd myautocmd FileType haskell setlocal omnifunc=necoghc#omnifunc
  let g:ycm_semantic_triggers = {'haskell':['.']}
'''

[[plugins]]
repo = 'ujihisa/ref-hoogle'
on_ft = ['haskell']

[[plugins]]
repo = 'ujihisa/unite-haskellimport'
on_ft = ['haskell']
# }}} HASKELL


# HTML {{{
[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['javascript', 'typescript', 'html', 'css']

[[plugins]]
repo  = 'hokaccha/vim-html5validator'
on_ft = ['javascript', 'typescript', 'html']

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_ft = ['javascript', 'typescript', 'html']

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript', 'html']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'typescript', 'html']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
hook_add = '''
  let g:js_indent_typescript = 1
'''

[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo  = 'clausreinke/typescript-tools'
on_ft = ['typescript']

# }}} HTML


# others {{{
[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = ['csv']


## ## PYTHON
## ##[[plugins]]
## ##repo = 'kevinw/pyflakes-vim'
## ##on_ft = ['python']

## [[plugins]]
## ##repo = 'majutsushi/tagbar'
## #{'autoload': {'commands': ['Tagbar',]

## [[plugins]]
## repo = 'h1mesuke/unite-outline'
## 'unite_sources': ['outline']

