return {
  {
    "nvim-treesitter/nvim-treesitter",
    lazy = true,
    -- event = "BufEnter",
    build = ":TSUpdate",
    opts = {
      auto_install = false,
      sync_install = false,
      highlight = {
        enable = true,
        disable = {},
      },
      indent = {
        enable = true,
        disable = {},
      },
      ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "diff",
        "fish",
        "gitignore",
        "go",
        "graphql",
        "help",
        "http",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "latex",
        "lua",
        "markdown",
        "markdown_inline",
        "ninja",
        "php",
        "python",
        "regex",
        "rust",
        "scss",
        "sql",
        "svelte",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
      },
      autotag = {
        enable = true,
      },
    }
  },
}
